import { expect, test, type Page } from '@playwright/test'
import { intelligence } from './fixtures.ts'

test.beforeEach(async ({ page }) => {
  await page.clock.install()
  await page.route('**/api/live-intel', (route) => route.fulfill({ json: intelligence }))
})

async function setHidden(page: Page, hidden: boolean) {
  await page.evaluate((value) => {
    Object.defineProperty(document, 'hidden', { configurable: true, value })
    Object.defineProperty(document, 'visibilityState', { configurable: true, value: value ? 'hidden' : 'visible' })
    document.dispatchEvent(new Event('visibilitychange'))
  }, hidden)
}

test('Start immediately confirms a running demo, adds events and preserves real intelligence', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.live-status-badge')).toHaveText('Sources current')
  const console = page.locator('.simulation-console')
  const status = page.locator('.simulation-status')
  await expect(console).toHaveAttribute('data-state', 'ready')
  await expect(status).toHaveAttribute('role', 'status')
  await expect(status).toContainText('Simulation ready')
  await expect(page.locator('.simulation-session-count')).toHaveText('+0')
  await expect(page.locator('.simulation-event-list li')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Reset demo', exact: true })).toBeDisabled()
  const selected = await page.locator('.queue-row[aria-pressed="true"]').getAttribute('aria-label')
  const records = await page.locator('.osint-list').allTextContents()

  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await expect(console).toHaveAttribute('data-state', 'running')
  await expect(status).toContainText('Simulation running')
  await expect(page.getByRole('button', { name: 'Pause simulation', exact: true })).toHaveAttribute('aria-pressed', 'true')
  // No clock advancement: the first result must be visible on the initial click.
  await expect(page.locator('.simulation-session-count')).toHaveText('+7')
  await expect(page.locator('.map-panel .map-readout data')).toHaveText('9,510')
  await expect(page.locator('.simulation-event-list li')).toHaveCount(1)
  await expect(page.locator('.simulation-event-list li').first()).toHaveAttribute('data-batch', '1')
  await expect(page.locator('.map-panel')).toContainText(/no (?:real )?traffic|not live traffic/i)
  expect(await page.locator('.osint-list').allTextContents()).toEqual(records)
  await expect(page.locator('.queue-row[aria-pressed="true"]')).toHaveAttribute('aria-label', selected!)
})

test('visible events advance by one batch with bounded history and no per-tick announcement', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  const status = await page.locator('.simulation-status').textContent()
  for (let batch = 2; batch <= 8; batch++) {
    await page.clock.fastForward(2600)
    await expect(page.locator('.simulation-session-count')).toHaveText(`+${batch * 7}`)
    await expect(page.locator('.simulation-event-list li')).toHaveCount(Math.min(3, batch))
    await expect(page.locator('.simulation-event-list li').first()).toHaveAttribute('data-batch', String(batch))
  }
  await expect(page.locator('.simulation-status')).toHaveText(status!)
  const events = page.locator('.simulation-event-list')
  expect(await events.evaluate((element) => Boolean(element.closest('[role="status"], [role="alert"], [role="log"], [aria-live="polite"], [aria-live="assertive"]')))).toBe(false)
  expect(await events.locator('li').evaluateAll((rows) => rows.map((row) => row.getAttribute('data-batch')))).toEqual(['8', '7', '6'])
  const regionalSum = await page.locator('.map-panel .map-node data').evaluateAll((nodes) => nodes.reduce((sum, node) => sum + Number(node.textContent!.replaceAll(',', '')), 0))
  expect(regionalSum).toBe(9559)
  await expect(page.locator('.map-panel .map-readout data')).toHaveText('9,559')
})

test('Pause freezes session and event history; Resume continues without a new immediate batch', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await page.clock.fastForward(2600)
  await page.getByRole('button', { name: 'Pause simulation', exact: true }).click()
  await expect(page.locator('.simulation-console')).toHaveAttribute('data-state', 'paused')
  await expect(page.locator('.simulation-status')).toContainText('Simulation paused')
  const history = await page.locator('.simulation-event-list').textContent()
  await page.clock.fastForward(26_000)
  await expect(page.locator('.simulation-session-count')).toHaveText('+14')
  await expect(page.locator('.simulation-event-list')).toHaveText(history!)
  const resume = page.getByRole('button', { name: 'Resume simulation', exact: true })
  await expect(resume).toHaveAttribute('aria-pressed', 'false')
  await resume.click()
  await expect(page.locator('.simulation-console')).toHaveAttribute('data-state', 'running')
  await expect(page.locator('.simulation-session-count')).toHaveText('+14')
  await page.clock.fastForward(2600)
  await expect(page.locator('.simulation-session-count')).toHaveText('+21')
  await expect(page.locator('.simulation-event-list li').first()).toHaveAttribute('data-batch', '3')
})

test('Reset stops an active run, clears its history and allows a fresh immediate start', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await page.clock.fastForward(2600)
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await expect(page.locator('.simulation-console')).toHaveAttribute('data-state', 'ready')
  await expect(page.locator('.simulation-status')).toContainText('Simulation ready')
  await expect(page.locator('.simulation-session-count')).toHaveText('+0')
  await expect(page.locator('.simulation-event-list li')).toHaveCount(0)
  await expect(page.locator('.map-panel .map-readout data')).toHaveText('9,503')
  await expect(page.getByRole('button', { name: 'Reset demo', exact: true })).toBeDisabled()
  await page.clock.fastForward(26_000)
  await expect(page.locator('.simulation-session-count')).toHaveText('+0')
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await expect(page.locator('.simulation-session-count')).toHaveText('+7')
  await expect(page.locator('.simulation-event-list li').first()).toHaveAttribute('data-batch', '1')
})

test('hidden tabs freeze simulation with an explicit background state and resume only one timer', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await setHidden(page, true)
  await expect(page.locator('.simulation-console')).toHaveAttribute('data-state', 'background')
  await expect(page.locator('.simulation-status')).toContainText('Paused in background')
  await page.clock.fastForward(26_000)
  await expect(page.locator('.simulation-session-count')).toHaveText('+7')
  await setHidden(page, false)
  await setHidden(page, false)
  await expect(page.locator('.simulation-console')).toHaveAttribute('data-state', 'running')
  await page.clock.fastForward(2600)
  await expect(page.locator('.simulation-session-count')).toHaveText('+14')
  await page.getByRole('button', { name: 'Pause simulation', exact: true }).click()
  await setHidden(page, true)
  await setHidden(page, false)
  await page.clock.fastForward(5200)
  await expect(page.locator('.simulation-console')).toHaveAttribute('data-state', 'paused')
  await expect(page.locator('.simulation-session-count')).toHaveText('+14')
})

test('Motion off keeps clear running feedback and numeric events without decorative animations', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Motion on', exact: true }).click()
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await expect(page.locator('.simulation-status')).toContainText('Simulation running')
  await expect(page.locator('.simulation-session-count')).toHaveText('+7')
  expect(await page.locator('.site-shell').evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
  await page.clock.fastForward(2600)
  await expect(page.locator('.simulation-session-count')).toHaveText('+14')
  expect(await page.locator('.site-shell').evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
})

test('system reduced motion preserves immediate simulation feedback with no animations', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Motion off', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await expect(page.locator('.simulation-status')).toContainText('Simulation running')
  await expect(page.locator('.simulation-session-count')).toHaveText('+7')
  await page.clock.fastForward(2600)
  await expect(page.locator('.simulation-session-count')).toHaveText('+14')
  expect(await page.locator('.site-shell').evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
})

test('simulation controls work from the keyboard and fit the narrowest supported screen', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await page.goto('/')
  const start = page.getByRole('button', { name: 'Start simulation', exact: true })
  await start.focus()
  await page.keyboard.press('Enter')
  const pause = page.getByRole('button', { name: 'Pause simulation', exact: true })
  await expect(pause).toBeFocused()
  await expect(page.locator('.simulation-session-count')).toHaveText('+7')
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Resume simulation', exact: true })).toBeFocused()
  await expect(page.locator('.simulation-status')).toContainText('Simulation paused')
  const reset = page.getByRole('button', { name: 'Reset demo', exact: true })
  await reset.focus()
  await page.keyboard.press('Enter')
  await expect(start).toBeVisible()
  await expect(page.locator('.simulation-session-count')).toHaveText('+0')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  for (const control of [start, reset]) {
    const box = await control.boundingBox()
    expect(box).not.toBeNull()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(320)
    expect(box!.height).toBeGreaterThanOrEqual(44)
  }
})
